<?php

// WARNING: DO NOT EDIT THIS FILE
// Many variables names and values in this file are hard coded 

// load coaches
include_once('calendars_config.php');
$coach_options = array('Any Coach');
if (isset($calendars_config)) {
	foreach($calendars_config as $cc) {
		if ($cc['type'] == 'coach') {
			$coach_options[] = $cc['name'];
		}
	}
}

$coach_type = 'select';
$coach_value = '';
if (count($coach_options) == 2) { 
	$coach_type = 'hidden';
	$coach_value = $coach_options[1];
}

include_once('appointment_types_config.php');
$appt_options = array('');
if (isset($appointment_types_config)) {
	foreach($appointment_types_config as $apptc) {
		if ($apptc['type'] != 'service') {
			$appt_options[] = $apptc['name'];
		}
	}
}

// define fields
$fields = array(
	array('type'=>'text',
		  'name'=>'name',
		  'label'=>'Name',
		  'required'=>true,
		  ),
	array('type'=>'text',
		  'name'=>'email',
		  'label'=>'Email',
		  'required'=>true,
		  ),
	array('type'=>'text',
		  'name'=>'phone',
		  'label'=>'Phone',
		  'required'=>true,
		  ),
	array('type'=>'select',
		  'name'=>'appointment_type',
		  'label'=>'Type of Appointment',
		  'options'=>$appt_options,
		  'onchange'=>'reset_datepicker()',
		  'required'=>true,
		  ),
	array('type'=>'radio',
		  'name'=>'loc',
		  'label'=>'Location',
		  'options'=>array('In Studio','Home Visit'),
		  'value'=>'In Studio',
		  'required'=>true,
		  ),
	/* address fields (display if loc = 'Home Visit') */
	array('type'=>'text',
		  'name'=>'address_1',
		  'label'=>'Address 1',
		  'display_condition'=>array('loc'=>'Home Visit'),
		  'required'=>true,
		  ),
	array('type'=>'text',
		  'name'=>'address_2',
		  'label'=>'Address 2',
		  'display_condition'=>array('loc'=>'Home Visit'),
		  ),
	array('type'=>'select',
		  'name'=>'city',
		  'label'=>'City',
		  'options'=>array('New York','Brooklyn','Queens', 'Long Island'),
		  'display_condition'=>array('loc'=>'Home Visit'),
		  'required'=>true,
		  ),
	array('type'=>'display',
		  'name'=>'state',
		  'label'=>'State',
		  'value'=>'NY',
		  'display_condition'=>array('loc'=>'Home Visit'),
		  ),
	array('type'=>'text',
		  'name'=>'zip',
		  'label'=>'Zip',
		  'display_condition'=>array('loc'=>'Home Visit'),
		  'required'=>true,
		  ),
	array('type'=>$coach_type,
		  'name'=>'coach',
		  'label'=>'Coach',
		  'options'=>$coach_options,
		  'value'=>$coach_value,
		  //'display_condition'=>array('appointment_type'=>array('Bike Fitting', 'Cleat Fitting','Lactate Testing')),
		  'required'=>true,
		  ),
	array('type'=>'appointment',
		  'name'=>'appointment',
		  'label'=>'Date & Time',
		  'required'=>true,
		  ),
	array('type'=>'textarea',
		  'name'=>'comments',
		  'label'=>'Comments/Notes',
		  'placeholder'=>'Let us know your shoes sizes and Pedal type.',
		  ),
	
);

?>